-- Finance Dashboard — relational schema aligned with JPA entities
-- (User @Table("users"), FinancialRecord @Table("financial_records"))
--
-- `record_date` maps to FinancialRecord.date (MySQL reserves `DATE` as a type name).
-- Portable DDL for H2 / PostgreSQL-style IDENTITY. For MySQL-specific syntax see schema-mysql.sql.
--
-- Enum values must match Java enums:
--   users.role: ADMIN | ANALYST | VIEWER
--   financial_records.type: INCOME | EXPENSE

DROP TABLE IF EXISTS financial_records;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL,
    is_active BOOLEAN,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT chk_users_role CHECK (role IN ('ADMIN', 'ANALYST', 'VIEWER'))
);

CREATE TABLE financial_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount DOUBLE PRECISION NOT NULL,
    type VARCHAR(16) NOT NULL,
    category VARCHAR(255) NOT NULL,
    record_date DATE NOT NULL,
    note VARCHAR(255),
    user_id BIGINT,
    CONSTRAINT chk_financial_records_amount CHECK (amount >= 1),
    CONSTRAINT chk_financial_records_type CHECK (type IN ('INCOME', 'EXPENSE')),
    CONSTRAINT fk_financial_records_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_financial_records_user_id ON financial_records (user_id);
CREATE INDEX idx_financial_records_record_date ON financial_records (record_date);
CREATE INDEX idx_financial_records_type ON financial_records (type);
